### ISSUE TITLE
coding style not following zig guideline

### ISSUE THREAD

**Issue by binarycraft007** [ianic/tls.zig#1]
https://github.com/ianic/tls.zig/blob/main/src/main.zig#L32
```zig
pub fn server(stream: anytype, opt: ServerOptions) !Connection(@TypeOf(stream));
pub fn client(stream: anytype, opt: ClientOptions) !Connection(@TypeOf(stream));
```
according to zig style guideline below, both functions should be TitleCase.
> f x is callable, and x's return type is type, then x should be TitleCase.

**Comment by ianic** [comment]
But the return type is not `type` it is struct of type `Connection(@TypeOf(stream))`.
Like, for example, [this](https://github.com/ziglang/zig/blob/fa95c89a717f283215e9fd3ea0b8ebcd1599a69b/lib/std/io/fixed_buffer_stream.zig#L112) from the std lib.
So I think it is following the guideline.

Please correct me if I'm wrong.

**Comment by binarycraft007** [comment]
> But the return type is not `type` it is struct of type `Connection(@TypeOf(stream))`. Like, for example, [this](https://github.com/ziglang/zig/blob/fa95c89a717f283215e9fd3ea0b8ebcd1599a69b/lib/std/io/fixed_buffer_stream.zig#L112) from the std lib. So I think it is following the guideline.
> 
> Please correct me if I'm wrong.

yes, you are correct, it's indeed an instance of Connection.
